### PR TITLE
Fixing Regex expressions and ensuring durations aren't evaluated as instant for scheduling

### LINKED ISSUE #167: Regex expressions for isValidTime don't seem to be working correctly

### PR DESCRIPTION
**Pull request by zaydtahir**
Closes #167

### CODE REVIEW

File: src/commands/Admin/lockdown.ts [hunk 1]
```diff
@@ -84,13 +85,15 @@ Possible units for duration are: seconds, minutes, hours, days, weeks, months (3
       roleId: role.value.id,
       messageId: message.id,
     });
-
+    
     if (isValidTime(durationOrTime.value)) {
+      logger.info('this ocvcured');
```
Comment (sahil-kale) [inline src/commands/Admin/lockdown.ts:90]: Typo, please make descriptive. I'm wondering, is this actually required?

**Review by sahil-kale — CHANGES_REQUESTED** [review]

**Review by sahil-kale — APPROVED** [review]
